import type { Metadata } from 'next';

import { Geist } from 'next/font/google';

import { cn } from '@/shared/lib/clsx/utils';

import '@styles/globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('antialiased', 'font-sans', geist.variable)}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
